
  require_relative '../node_modules/react-native/scripts/react_native_pods'
  require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
  
  platform :ios, '11.0'
  
  target 'react_native_boilerplate' do
    config = use_native_modules!
  
    use_react_native!(:path => config["reactNativePath"])
  
    target 'react_native_boilerplateTests' do
      inherit! :complete
      # Pods for testing
    end
  
   
  end
  
  target 'react_native_boilerplate-tvOS' do
    # Pods for react_native_boilerplate-tvOS
  
    target 'react_native_boilerplate-tvOSTests' do
      inherit! :search_paths
      # Pods for testing
    end
  end
  